title: jeonghyun Lim
description: Backend Developer
site_title: "@jeonghyunLim"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: limzzum
blog_url: https://zammanboss.tistory.com
email: chfhddl1234@naver.com

# absolute or relative
profile_picture: assets/images/dev-jeans.png

# Google Analytics ID
google_analytics:
